# Generated by tools/gen_proxies.py -- do not edit.
# Re-exports the types-openpyxl stub (typeshed, Apache-2.0) for the openpyxl module
# aliased at this path; see _compat.py.
from openpyxl.compat.strings import *
